---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: pcfdemo
  - name: final-release
  - name: version

outputs:
  - name: prepare-prod

run:
  path: pcfdemo/ci/tasks/prepare-prod.sh
  args: [
    --input-dir, final-release,
    --output-dir, prepare-prod,
    --version-file, version/number,
    --input-manifest, pcfdemo/manifest.yml,
    --artifactId, pcf-demo,
    --packaging, war
  ]
